# **Prediksi Polusi Udara**

## **Import Library**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import tensorflow as tf
from tensorflow.keras.layers import Dense, LSTM

## **Load Data**

In [14]:
df_clean = pd.read_csv("../data/processed/clean_data_2025-06-21_to_2025-06-24.csv", index_col=0, parse_dates=True)

df_clean

,Temperature,Humidity,PM2.5,PM10,CO,CO2
created_at,,,,,,
2025-06-21 07:00:15+07:00,24.8,84.3,52.7,72.50000,0.59860,403.34171
2025-06-21 07:01:04+07:00,24.8,84.1,50.4,66.70000,0.56109,403.40472
2025-06-21 07:01:53+07:00,24.8,84.0,51.7,74.00000,0.54466,403.36261
2025-06-21 07:02:43+07:00,24.9,83.6,49.7,65.90000,0.55447,403.30020
2025-06-21 07:03:32+07:00,24.9,83.3,51.6,72.70000,0.57113,403.29333
...,...,...,...,...,...,...
2025-06-24 06:54:30+07:00,24.4,84.1,132.5,191.30000,1.02385,406.81610
2025-06-24 06:55:19+07:00,24.4,83.9,123.7,183.50000,1.00797,406.69278
2025-06-24 06:56:08+07:00,24.4,83.9,113.6,167.50000,1.00010,406.77890
2025-06-24 06:56:58+07:00,24.4,83.8,114.1,167.80000,1.00534,406.49930
2025-06-24 06:58:39+07:00,24.5,83.7,107.3,159.60001,1.01324,406.48737

In [15]:
df_resampled = df_clean.resample('1min').mean().interpolate(method='linear')

In [16]:
df_resampled

,Temperature,Humidity,PM2.5,PM10,CO,CO2
created_at,,,,,,
2025-06-21 07:00:00+07:00,24.80,84.300,52.700,72.500000,0.598600,403.341710
2025-06-21 07:01:00+07:00,24.80,84.050,51.050,70.350000,0.552875,403.383665
2025-06-21 07:02:00+07:00,24.90,83.600,49.700,65.900000,0.554470,403.300200
2025-06-21 07:03:00+07:00,24.90,83.300,51.600,72.700000,0.571130,403.293330
2025-06-21 07:04:00+07:00,24.90,83.300,48.300,67.900000,0.566090,403.293330
...,...,...,...,...,...,...
2025-06-24 06:54:00+07:00,24.40,84.100,132.500,191.300000,1.023850,406.816100
2025-06-24 06:55:00+07:00,24.40,83.900,123.700,183.500000,1.007970,406.692780
2025-06-24 06:56:00+07:00,24.40,83.850,113.850,167.650000,1.002720,406.639100
2025-06-24 06:57:00+07:00,24.45,83.775,110.575,163.625005,1.007980,406.563235
2025-06-24 06:58:00+07:00,24.50,83.700,107.300,159.600010,1.013240,406.487370